version: "3.4"

networks:
  grant:
    driver: bridge

services:
  grant-redis:
    container_name: grant-redis
    image: redis:latest
    networks:
      - grant
  grant-web:
    container_name: grant-web
    image: grant-web-builder 
    build:
      context: .
      target: builder 
    ports:
      - "3333:3333"
    environment:
      - "REDIS_URL=${REDIS_URL-redis://grant-redis:6379}"
      - BAT_SETTLEMENT_ADDRESS
      - GRANT_SIGNATOR_PUBLIC_KEY
      - GRANT_WALLET_CARD_ID
      - GRANT_WALLET_PRIVATE_KEY
      - GRANT_WALLET_PUBLIC_KEY
      - TOKEN_LIST
      - UPHOLD_ACCESS_TOKEN
    depends_on:
      - grant-redis
    networks:
      - grant
